
import sys
import os
from datetime import timedelta

# Add backend directory to python path
sys.path.append(os.path.join(os.getcwd(), 'backend'))

from app.config import settings
from app.utils.security import create_access_token, decode_access_token
from jose import jwt, JWTError

print(f"Algorithm: {settings.JWT_ALGORITHM}")
print(f"Secret Key: '{settings.JWT_SECRET_KEY}' (Length: {len(settings.JWT_SECRET_KEY)})")

# Test 1: Create and Decode internal token
data = {"sub": 1, "email": "admin@example.com", "role": "admin"}
token = create_access_token(data)
print(f"\nGenerated Token: {token}")

decoded = decode_access_token(token)
print(f"Decoded Internal: {decoded}")

if decoded is None:
    print("FAILED to decode internal token!")
    try:
        jwt.decode(token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM])
    except Exception as e:
        print(f"Detailed Error: {e}")

# Test 2: Test the reported token from logs (if available, otherwise skip)
# This is the token from Step 209 which was generated by test_login.py
external_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3Njc0MDQyOTAsImlhdCI6MTc2NzMxNzg5MH0.xb41JZh-O1w_gexdswRQX-zPcGa67UMOQpemixjZGP0"
print(f"\nTesting External Token: {external_token}")
decoded_ext = decode_access_token(external_token)
print(f"Decoded External: {decoded_ext}")

if decoded_ext is None:
    print("FAILED to decode external token!")
    try:
        jwt.decode(external_token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM])
    except Exception as e:
        print(f"Detailed Error: {e}")
